'use client';

import { useEffect, useMemo, useState } from 'react';
import { Globe2, HeartPulse, MessageCircle, TrendingUp } from 'lucide-react';
import { Badge, Card } from '@/components/ui';
import { initialMarketingPosts } from '@/lib/mock-data';
import { formatDateLabel, loadLocalData, saveLocalData } from '@/lib/utils';
import type { MarketingPost } from '@/lib/mock-data';

const STORAGE_MARKETING = 'ingweplex-marketing-posts';

const platformOptions: MarketingPost['platform'][] = ['LinkedIn', 'Instagram', 'X', 'TikTok'];

const getEngagementRate = (post: MarketingPost) => {
  if (!post.views) {
    return 0;
  }

  const totalEngagement = post.likes + post.comments + post.shares + post.saves;
  return (totalEngagement / post.views) * 100;
};

const scoreBadge = (value: number) => {
  if (value >= 5) return 'success';
  if (value >= 3) return 'warning';
  return 'danger';
};

export default function MarketingPage() {
  const [posts, setPosts] = useState<MarketingPost[]>(initialMarketingPosts);
  const [draft, setDraft] = useState<MarketingPost>({
    id: 'M0',
    platform: 'LinkedIn',
    title: '',
    likes: 0,
    comments: 0,
    shares: 0,
    saves: 0,
    views: 0,
    date: new Date().toISOString().slice(0, 10),
  });

  useEffect(() => {
    const storedPosts = loadLocalData<MarketingPost[]>(STORAGE_MARKETING, initialMarketingPosts);
    setPosts(storedPosts);
  }, []);

  useEffect(() => {
    saveLocalData(STORAGE_MARKETING, posts);
  }, [posts]);

  const sortedPosts = useMemo(
    () => [...posts].sort((a, b) => getEngagementRate(b) - getEngagementRate(a)),
    [posts],
  );

  const averageEngagement = useMemo(() => {
    if (!posts.length) return 0;
    return posts.reduce((sum, post) => sum + getEngagementRate(post), 0) / posts.length;
  }, [posts]);

  const addPost = () => {
    setPosts((current) => [
      { ...draft, id: `M${current.length + 1}` },
      ...current,
    ]);
    setDraft((prev) => ({ ...prev, title: '', likes: 0, comments: 0, shares: 0, saves: 0, views: 0 }));
  };

  return (
    <main className="min-h-screen bg-slate-50 px-4 py-8 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl space-y-6">
        <section className="rounded-3xl bg-white p-6 shadow-soft">
          <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
            <div>
              <p className="text-sm uppercase tracking-[0.32em] text-orange-600">Marketing Analytics</p>
              <h1 className="mt-3 text-3xl font-semibold text-slate-900">Performance insights and content signal</h1>
              <p className="mt-2 text-slate-600">Track engagement, identify winning formats, and connect content to discovery calls.</p>
            </div>
          </div>
        </section>

        <div className="grid gap-6 lg:grid-cols-4">
          <Card className="rounded-3xl p-5">
            <p className="text-sm font-medium uppercase tracking-[0.24em] text-slate-500">Total reach</p>
            <p className="mt-4 text-3xl font-semibold text-slate-900">{posts.reduce((sum, post) => sum + post.views, 0).toLocaleString()}</p>
            <p className="mt-2 text-xs text-slate-500">All channels combined.</p>
          </Card>
          <Card className="rounded-3xl p-5">
            <p className="text-sm font-medium uppercase tracking-[0.24em] text-slate-500">Engagement rate</p>
            <p className="mt-4 text-3xl font-semibold text-slate-900">{averageEngagement.toFixed(1)}%</p>
            <p className="mt-2 text-xs text-slate-500">Channel-normalized benchmark.</p>
          </Card>
          <Card className="rounded-3xl p-5">
            <p className="text-sm font-medium uppercase tracking-[0.24em] text-slate-500">Discovery calls</p>
            <p className="mt-4 text-3xl font-semibold text-slate-900">12</p>
            <p className="mt-2 text-xs text-slate-500">Leads generated by campaigns.</p>
          </Card>
          <Card className="rounded-3xl p-5">
            <p className="text-sm font-medium uppercase tracking-[0.24em] text-slate-500">Top channel</p>
            <p className="mt-4 text-3xl font-semibold text-slate-900">LinkedIn</p>
            <p className="mt-2 text-xs text-slate-500">Highest conversion signal.</p>
          </Card>
        </div>

        <section className="grid gap-6 xl:grid-cols-[1.2fr,0.8fr]">
          <Card className="rounded-3xl p-6">
            <div className="flex items-center gap-3 text-slate-700">
              <Globe2 className="h-5 w-5 text-orange-600" />
              <p className="text-xs uppercase tracking-[0.24em] text-slate-500">Recent posts</p>
            </div>
            <div className="mt-6 space-y-4">
              {sortedPosts.slice(0, 6).map((post) => (
                <div key={post.id} className="rounded-3xl border border-slate-200 bg-slate-50 p-4">
                  <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                    <div>
                      <p className="font-semibold text-slate-900">{post.title}</p>
                      <p className="text-xs text-slate-500">{post.platform} · {formatDateLabel(post.date)}</p>
                    </div>
                    <Badge variant={scoreBadge(getEngagementRate(post))}>{getEngagementRate(post).toFixed(1)}%</Badge>
                  </div>
                  <div className="mt-3 flex flex-wrap gap-3 text-xs text-slate-500">
                    <span>Likes {post.likes}</span>
                    <span>Comments {post.comments}</span>
                    <span>Shares {post.shares}</span>
                    <span>Saves {post.saves}</span>
                    <span>Views {post.views.toLocaleString()}</span>
                  </div>
                </div>
              ))}
            </div>
          </Card>

          <aside className="space-y-6">
            <Card className="rounded-3xl p-6">
              <div className="flex items-center gap-3 text-slate-700">
                <HeartPulse className="h-5 w-5 text-orange-600" />
                <p className="text-sm uppercase tracking-[0.24em] text-slate-500">Content scorecard</p>
              </div>
              <div className="mt-5 space-y-3 text-sm text-slate-600">
                <div className="flex items-center justify-between rounded-3xl bg-slate-50 px-4 py-3">
                  <div>
                    <p className="font-semibold text-slate-900">LinkedIn Follower Growth</p>
                    <p className="text-xs text-slate-500">Target ≥ 10%</p>
                  </div>
                  <Badge variant="success">On target</Badge>
                </div>
                <div className="flex items-center justify-between rounded-3xl bg-slate-50 px-4 py-3">
                  <div>
                    <p className="font-semibold text-slate-900">Content Pieces Published</p>
                    <p className="text-xs text-slate-500">Target ≥ 15/month</p>
                  </div>
                  <Badge variant="success">✓</Badge>
                </div>
                <div className="flex items-center justify-between rounded-3xl bg-slate-50 px-4 py-3">
                  <div>
                    <p className="font-semibold text-slate-900">Discovery Calls Booked</p>
                    <p className="text-xs text-slate-500">Weekly conversion signal</p>
                  </div>
                  <Badge variant="warning">Tracking</Badge>
                </div>
              </div>
            </Card>
            <Card className="rounded-3xl p-6">
              <div className="flex items-center gap-3 text-slate-700">
                <MessageCircle className="h-5 w-5 text-orange-600" />
                <p className="text-sm uppercase tracking-[0.24em] text-slate-500">Performance action</p>
              </div>
              <p className="mt-4 text-sm text-slate-600">When engagement climbs above 5%, the content should be amplified immediately across the highest-converting channel.</p>
            </Card>
          </aside>
        </section>

        <Card className="rounded-3xl p-6">
          <div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between">
            <div>
              <p className="text-sm uppercase tracking-[0.24em] text-slate-500">Post performance input</p>
              <h2 className="mt-2 text-lg font-semibold text-slate-900">Quick-add weekly entry</h2>
            </div>
          </div>

          <div className="mt-6 grid gap-4 lg:grid-cols-3">
            <label className="space-y-2 text-sm text-slate-700">
              Platform
              <select
                value={draft.platform}
                onChange={(event) => setDraft((prev) => ({ ...prev, platform: event.target.value as MarketingPost['platform'] }))}
                className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none"
              >
                {platformOptions.map((platform) => (
                  <option key={platform} value={platform}>{platform}</option>
                ))}
              </select>
            </label>
            <label className="space-y-2 text-sm text-slate-700">
              Post title
              <input
                value={draft.title}
                onChange={(event) => setDraft((prev) => ({ ...prev, title: event.target.value }))}
                className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none"
              />
            </label>
            <label className="space-y-2 text-sm text-slate-700">
              Date
              <input
                type="date"
                value={draft.date}
                onChange={(event) => setDraft((prev) => ({ ...prev, date: event.target.value }))}
                className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none"
              />
            </label>
          </div>

          <div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
            {['likes', 'comments', 'shares', 'saves'].map((field) => (
              <label key={field} className="space-y-2 text-sm text-slate-700">
                {field.charAt(0).toUpperCase() + field.slice(1)}
                <input
                  type="number"
                  min={0}
                  value={draft[field as keyof MarketingPost] as number}
                  onChange={(event) => setDraft((prev) => ({ ...prev, [field]: Number(event.target.value) }))}
                  className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none"
                />
              </label>
            ))}
            <label className="space-y-2 text-sm text-slate-700">
              Views
              <input
                type="number"
                min={0}
                value={draft.views}
                onChange={(event) => setDraft((prev) => ({ ...prev, views: Number(event.target.value) }))}
                className="w-full rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm outline-none"
              />
            </label>
          </div>

          <div className="mt-6 flex justify-end">
            <button
              onClick={addPost}
              className="rounded-2xl bg-orange-600 px-5 py-3 text-sm font-semibold text-white transition hover:bg-orange-700"
            >
              Add performance entry
            </button>
          </div>
        </Card>
      </div>
    </main>
  );
}
